name = "bmtest1"
pages_build_output_dir = "dist"
compatibility_date = "2026-09-10"

[[d1_databases]]
binding = "DB"
database_name = "boomyung-sitea-db"
database_id = "dd61512c-7b4b-4c7f-837c-be170b4d83ae"

[ai]
binding = "AI"
